# Configuración para Air
root = "./"

[build]
  cmd = "cmd /C \"set GOOS=windows && set GOARCH=arm64 && go build -o ./tmp/main.exe .\""
  bin = "./tmp/main.exe"
  include_ext = ["go"]
  include_dir = ["cmd", "routes", "db"]
  exclude_dir = ["tmp"]

[log]
  level = "info"