CREATE TABLE procesos (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NVNUMERO INT NOT NULL,
    NVESTADO NVARCHAR(MAX) DEFAULT NULL,
    FECHA_NV NVARCHAR(MAX) DEFAULT NULL,
    FECHA_ENTREGA NVARCHAR(MAX) DEFAULT NULL,
    CONCAUTO NVARCHAR(MAX) DEFAULT NULL,
    CODPROD NVARCHAR(MAX) DEFAULT NULL,
    NVCANT INT DEFAULT NULL,
    CANT_FACT INT DEFAULT NULL,
    DIF_FACT INT DEFAULT NULL,
    NVPRECIO DECIMAL(10,2) DEFAULT NULL,
    DETPROD NVARCHAR(MAX) DEFAULT NULL,
    NOMAUX NVARCHAR(MAX) DEFAULT NULL,
    CODPROC NVARCHAR(MAX) DEFAULT NULL,
    PROCESO NVARCHAR(MAX) DEFAULT NULL,
    DESCPROC NVARCHAR(MAX) DEFAULT NULL,
    TIEMPO INT DEFAULT NULL,
    CANTPROD INT DEFAULT NULL
);

CREATE TABLE procesos2 (
    ID INT PRIMARY KEY,
    ESTADO_PROC NVARCHAR(MAX) DEFAULT 'PENDIENTE',
    CANT_PROD INT DEFAULT 0,
    CANT_A_PROD INT DEFAULT NULL,
    PLACA NVARCHAR(MAX) DEFAULT NULL,
    PLACAS_USADAS NVARCHAR(MAX) DEFAULT NULL,
    PLACAS_BUENAS NVARCHAR(MAX) DEFAULT NULL,
    PLACAS_MALAS NVARCHAR(MAX) DEFAULT NULL,
    TIEMPO_TOTAL DECIMAL(10,2) DEFAULT NULL,
    NUMERO_PERSONAS INT DEFAULT 0,
    STOCK NVARCHAR(MAX) DEFAULT NULL,
    [USER] NVARCHAR(MAX) DEFAULT NULL,
    STOCK_CANT INT DEFAULT 0,

    FOREIGN KEY (ID) REFERENCES procesos(ID)
);

CREATE TABLE nv_hechas(
    NVENTA INT DEFAULT NULL
);

CREATE TABLE inventario (
	ID INT PRIMARY KEY,
    placa NVARCHAR(MAX),
    cantidad INT DEFAULT NULL,
    cantidad_total_usada INT DEFAULT 0,
    fecha_compra NVARCHAR(MAX) DEFAULT NULL,
    precio_pp DECIMAL(10,2) DEFAULT NULL,
    precio_total DECIMAL(10,2) DEFAULT NULL,
    
)
CREATE TABLE users (
    ID INT PRIMARY KEY IDENTITY(1,1),
    USERNAME NVARCHAR(MAX) NOT NULL,
    PASSWORD NVARCHAR(MAX) NOT NULL,
    NOMBRE NVARCHAR(MAX) DEFAULT NULL,
    APELLIDO NVARCHAR(MAX) DEFAULT NULL,
    ROL NVARCHAR(MAX) DEFAULT NULL,
    procesos NVARCHAR(MAX) DEFAULT NULL
);

CREATE TABLE PROCESOS (
    ID INT PRIMARY KEY,
    CANT_A_FABRICAR INT DEFAULT NULL,
    PRIORITY INT DEFAULT NULL,
    PLACAS_A_USAR NVARCHAR(MAX) DEFAULT NULL,
    CANTIDAD_PLACAS NVARCHAR(MAX) DEFAULT NULL,
    FOREIGN KEY (ID) REFERENCES procesos(ID)
);